-- =============================================================================
-- SUPABASE DATABASE SCHEMA CHO TIKTOK COMMENTS SCRAPER WEB APP
-- Chạy đoạn mã này trong: Supabase Dashboard -> SQL Editor -> New query -> Run
-- =============================================================================

-- 1. Bảng quản lý người dùng (users)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_id TEXT UNIQUE NOT NULL,
    email TEXT NOT NULL,
    name TEXT,
    avatar TEXT,
    credits INTEGER DEFAULT 3,
    is_vip BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    last_login TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Tạo Index để tối ưu tìm kiếm theo google_id và email
CREATE INDEX IF NOT EXISTS idx_users_google_id ON public.users (google_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (email);

-- Bật Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Cho phép toàn quyền truy cập thông qua Supabase Service Key / Anon Key
DROP POLICY IF EXISTS "Allow full access for users" ON public.users;
CREATE POLICY "Allow full access for users" ON public.users
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- 2. Bảng nhật ký cào dữ liệu (scrape_logs)
CREATE TABLE IF NOT EXISTS public.scrape_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    video_id TEXT NOT NULL,
    comments_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_scrape_logs_user_id ON public.scrape_logs (user_id);

ALTER TABLE public.scrape_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access for scrape_logs" ON public.scrape_logs;
CREATE POLICY "Allow full access for scrape_logs" ON public.scrape_logs
    FOR ALL
    USING (true)
    WITH CHECK (true);
